name: Build .NET
on:
  workflow_call:
    inputs:
      SDK_VERSION:
        type: string
        required: true
        description: The version of the .NET SDK to use when building.
      SOLUTION_DIR:
        type: string
        required: true
        description: The directory that contains the solution file to build.
      VERSION:
        type: string
        required: true
      IS_DEPLOYABLE:
        type: boolean
        required: true
      CONTAINS_LIBRARIES:
        type: boolean
        required: false
        default: false
env:
  BUILD_CONFIG: Release
  VERSION_NUMBER: "${{inputs.VERSION + github.run_id}}${{ inputs.IS_DEPLOYABLE ? '-rc' : '' }}"
jobs:
  dotnet-build:
    name: Run build and test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.SOLUTION_DIR }}
    steps:
      - run: echo "Version is ${{ env.VERSION_NUMBER }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.SDK_VERSION }}
      - run: dotnet build --nologo -c "${{ env.BUILD_CONFIG }}" -v minimal -p:Version="${{ inputs.VERSION }}"
      - run: dotnet test --nologo --no-build -c "${{ env.BUILD_CONFIG }}" -v minimal
  # dotnet-pack:
  #   needs: dotnet-build
  #   runs-on: ubuntu-latest
  #   steps:


