name: Deploy example lib
on:
  push:
    branches:
      - release/[0-9]+.[0-9]+.[0-9]+
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Parse version number
        run: |
          echo "VERSION=1.3.1" >> $GITHUB_ENV
      - uses: ./.github/workflows/build-dotnet.yaml
        with:
          SDK_VERSION: 6.0.x
          SOLUTION_DIR: src/example-library
          VERSION: ${{ env.VERSION }}
          CONTAINS_LIBRARIES: true
          IS_DEPLOYABLE: falsetrue