name: Deploy example lib
on:
  push:
    branches:
      - release/[0-9]+.[0-9]+.[0-9]+
jobs:
  deploy:
    uses: willwolfram18/dotnet-build-ideas/.github/workflows/build-dotnet.yaml@main
    with:
      SDK_VERSION: 6.0.x
      SOLUTION_DIR: src/example-library
      VERSION: '0.1.0'
      CONTAINS_LIBRARIES: true
      IS_DEPLOYABLE: true